micronaut:
  application:
    name: bepy
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/task
    driverClassName: org.postgresql.Driver
    username: postgres
    password: diego
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
grpc:
  server:
    port: 3009
    keep-alive-time: 3h
    max-inbound-message-size: 1024
    ssl:
      cert-chain: 'file://path/to/my.cert'
      private-key: 'classpath:my.key'